import { requireAuth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { revalidatePath } from 'next/cache';
import { Nav } from '@/components/Nav';
import { RoundStatus } from '@prisma/client';

async function refresh() { 'use server'; revalidatePath('/admin'); }

export default async function Page() {
  await requireAuth();
  const [players, leagues, seasons, rounds, boxes, allocations, categories] = await Promise.all([
    prisma.player.findMany({ orderBy: { displayName: 'asc' } }),
    prisma.league.findMany({ orderBy: { createdAt: 'desc' } }),
    prisma.season.findMany({ include: { league: true }, orderBy: [{ year: 'desc' }] }),
    prisma.round.findMany({ include: { season: true }, orderBy: [{ startDate: 'desc' }] }),
    prisma.setBox.findMany({ include: { round: true, boxOwner: true }, orderBy: { setName: 'asc' } }),
    prisma.packAllocation.findMany({ include: { round: true, player: true } }),
    prisma.pointCategory.findMany({ orderBy: { name: 'asc' } }),
  ]);

  return <main className="p-8 space-y-8"><Nav /><h1 className="text-3xl font-bold">Admin Setup</h1>

<section><h2 className="text-xl font-semibold">Players</h2><form action={async (fd)=>{'use server';await prisma.player.create({data:{name:String(fd.get('name')),displayName:String(fd.get('displayName')),email:String(fd.get('email')||'')||null,active:fd.get('active')==='on',isAdmin:fd.get('isAdmin')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="name" className="border p-1 bg-zinc-900"/><input name="displayName" placeholder="display name" className="border p-1 bg-zinc-900"/><input name="email" placeholder="email" className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked/> active</label><label><input type="checkbox" name="isAdmin"/> admin</label><button className="border px-2">Add</button></form>
{players.map(p=><form key={p.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.player.delete({where:{id:p.id}}); else await prisma.player.update({where:{id:p.id},data:{name:String(fd.get('name')),displayName:String(fd.get('displayName')),email:String(fd.get('email')||'')||null,active:fd.get('active')==='on',isAdmin:fd.get('isAdmin')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={p.name} className="border p-1 bg-zinc-900"/><input name="displayName" defaultValue={p.displayName} className="border p-1 bg-zinc-900"/><input name="email" defaultValue={p.email ?? ''} className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked={p.active}/> active</label><label><input type="checkbox" name="isAdmin" defaultChecked={p.isAdmin}/> admin</label><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">League</h2><form action={async(fd)=>{'use server';await prisma.league.create({data:{name:String(fd.get('name')),slug:String(fd.get('slug')),description:String(fd.get('description')||'')||null,appDisplayName:String(fd.get('appDisplayName')||'Box League')}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="name" className="border p-1 bg-zinc-900"/><input name="slug" placeholder="slug" className="border p-1 bg-zinc-900"/><input name="description" placeholder="description" className="border p-1 bg-zinc-900"/><input name="appDisplayName" placeholder="app display name" className="border p-1 bg-zinc-900"/><button className="border px-2">Add</button></form>
{leagues.map(l=><form key={l.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.league.delete({where:{id:l.id}}); else await prisma.league.update({where:{id:l.id},data:{name:String(fd.get('name')),slug:String(fd.get('slug')),description:String(fd.get('description')||'')||null,appDisplayName:String(fd.get('appDisplayName'))}});await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={l.name} className="border p-1 bg-zinc-900"/><input name="slug" defaultValue={l.slug} className="border p-1 bg-zinc-900"/><input name="description" defaultValue={l.description ?? ''} className="border p-1 bg-zinc-900"/><input name="appDisplayName" defaultValue={l.appDisplayName} className="border p-1 bg-zinc-900"/><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">Seasons</h2><form action={async(fd)=>{'use server';await prisma.season.create({data:{leagueId:String(fd.get('leagueId')),name:String(fd.get('name')),year:Number(fd.get('year')),startDate:new Date(String(fd.get('startDate'))),endDate:fd.get('endDate')?new Date(String(fd.get('endDate'))):null,active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="leagueId" className="border p-1 bg-zinc-900">{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input name="name" placeholder="name" className="border p-1 bg-zinc-900"/><input name="year" type="number" placeholder="year" className="border p-1 bg-zinc-900"/><input name="startDate" type="date" className="border p-1 bg-zinc-900"/><input name="endDate" type="date" className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active"/> active</label><button className="border px-2">Add</button></form>
{seasons.map(s=><form key={s.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.season.delete({where:{id:s.id}}); else await prisma.season.update({where:{id:s.id},data:{leagueId:String(fd.get('leagueId')),name:String(fd.get('name')),year:Number(fd.get('year')),startDate:new Date(String(fd.get('startDate'))),endDate:fd.get('endDate')?new Date(String(fd.get('endDate'))):null,active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="leagueId" defaultValue={s.leagueId} className="border p-1 bg-zinc-900">{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input name="name" defaultValue={s.name} className="border p-1 bg-zinc-900"/><input name="year" type="number" defaultValue={s.year} className="border p-1 bg-zinc-900"/><input name="startDate" type="date" defaultValue={s.startDate.toISOString().slice(0,10)} className="border p-1 bg-zinc-900"/><input name="endDate" type="date" defaultValue={s.endDate?.toISOString().slice(0,10) ?? ''} className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked={s.active}/> active</label><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">Rounds</h2><form action={async(fd)=>{'use server';await prisma.round.create({data:{seasonId:String(fd.get('seasonId')),name:String(fd.get('name')),monthNumber:Number(fd.get('monthNumber')),startDate:new Date(String(fd.get('startDate'))),endDate:fd.get('endDate')?new Date(String(fd.get('endDate'))):null,status:fd.get('status') as RoundStatus}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="seasonId" className="border p-1 bg-zinc-900">{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="name" placeholder="name" className="border p-1 bg-zinc-900"/><input name="monthNumber" type="number" className="border p-1 bg-zinc-900"/><input name="startDate" type="date" className="border p-1 bg-zinc-900"/><input name="endDate" type="date" className="border p-1 bg-zinc-900"/><select name="status" className="border p-1 bg-zinc-900"><option>PLANNED</option><option>ACTIVE</option><option>COMPLETED</option></select><button className="border px-2">Add</button></form>
{rounds.map(r=><form key={r.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.round.delete({where:{id:r.id}}); else await prisma.round.update({where:{id:r.id},data:{seasonId:String(fd.get('seasonId')),name:String(fd.get('name')),monthNumber:Number(fd.get('monthNumber')),startDate:new Date(String(fd.get('startDate'))),endDate:fd.get('endDate')?new Date(String(fd.get('endDate'))):null,status:fd.get('status') as RoundStatus}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="seasonId" defaultValue={r.seasonId} className="border p-1 bg-zinc-900">{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="name" defaultValue={r.name} className="border p-1 bg-zinc-900"/><input name="monthNumber" type="number" defaultValue={r.monthNumber} className="border p-1 bg-zinc-900"/><input name="startDate" type="date" defaultValue={r.startDate.toISOString().slice(0,10)} className="border p-1 bg-zinc-900"/><input name="endDate" type="date" defaultValue={r.endDate?.toISOString().slice(0,10) ?? ''} className="border p-1 bg-zinc-900"/><select name="status" defaultValue={r.status} className="border p-1 bg-zinc-900"><option>PLANNED</option><option>ACTIVE</option><option>COMPLETED</option></select><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">Set / Boxes</h2><form action={async(fd)=>{'use server';await prisma.setBox.create({data:{roundId:String(fd.get('roundId')),setName:String(fd.get('setName')),setCode:String(fd.get('setCode')),boxType:String(fd.get('boxType')),boxOwnerId:String(fd.get('boxOwnerId')||'')||null,totalPacks:Number(fd.get('totalPacks')),notes:String(fd.get('notes')||'')||null}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="roundId" className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input name="setName" placeholder="setName" className="border p-1 bg-zinc-900"/><input name="setCode" placeholder="setCode" className="border p-1 bg-zinc-900"/><input name="boxType" placeholder="boxType" className="border p-1 bg-zinc-900"/><select name="boxOwnerId" className="border p-1 bg-zinc-900"><option value="">(none)</option>{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="totalPacks" type="number" className="border p-1 bg-zinc-900"/><input name="notes" placeholder="notes" className="border p-1 bg-zinc-900"/><button className="border px-2">Add</button></form>
{boxes.map(b=><form key={b.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.setBox.delete({where:{id:b.id}}); else await prisma.setBox.update({where:{id:b.id},data:{roundId:String(fd.get('roundId')),setName:String(fd.get('setName')),setCode:String(fd.get('setCode')),boxType:String(fd.get('boxType')),boxOwnerId:String(fd.get('boxOwnerId')||'')||null,totalPacks:Number(fd.get('totalPacks')),notes:String(fd.get('notes')||'')||null}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="roundId" defaultValue={b.roundId} className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input name="setName" defaultValue={b.setName} className="border p-1 bg-zinc-900"/><input name="setCode" defaultValue={b.setCode} className="border p-1 bg-zinc-900"/><input name="boxType" defaultValue={b.boxType} className="border p-1 bg-zinc-900"/><select name="boxOwnerId" defaultValue={b.boxOwnerId ?? ''} className="border p-1 bg-zinc-900"><option value="">(none)</option>{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="totalPacks" type="number" defaultValue={b.totalPacks} className="border p-1 bg-zinc-900"/><input name="notes" defaultValue={b.notes ?? ''} className="border p-1 bg-zinc-900"/><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">Pack allocations</h2><form action={async(fd)=>{'use server';await prisma.packAllocation.create({data:{roundId:String(fd.get('roundId')),playerId:String(fd.get('playerId')),packsAssigned:Number(fd.get('packsAssigned')),packsOpened:Number(fd.get('packsOpened')),notes:String(fd.get('notes')||'')||null}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="roundId" className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select name="playerId" className="border p-1 bg-zinc-900">{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="packsAssigned" type="number" className="border p-1 bg-zinc-900"/><input name="packsOpened" type="number" className="border p-1 bg-zinc-900"/><input name="notes" placeholder="notes" className="border p-1 bg-zinc-900"/><button className="border px-2">Add</button></form>
{allocations.map(a=><form key={a.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.packAllocation.delete({where:{id:a.id}}); else await prisma.packAllocation.update({where:{id:a.id},data:{roundId:String(fd.get('roundId')),playerId:String(fd.get('playerId')),packsAssigned:Number(fd.get('packsAssigned')),packsOpened:Number(fd.get('packsOpened')),notes:String(fd.get('notes')||'')||null}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="roundId" defaultValue={a.roundId} className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select name="playerId" defaultValue={a.playerId} className="border p-1 bg-zinc-900">{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="packsAssigned" type="number" defaultValue={a.packsAssigned} className="border p-1 bg-zinc-900"/><input name="packsOpened" type="number" defaultValue={a.packsOpened} className="border p-1 bg-zinc-900"/><input name="notes" defaultValue={a.notes ?? ''} className="border p-1 bg-zinc-900"/><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section><h2 className="text-xl font-semibold">Point categories</h2><form action={async(fd)=>{'use server';await prisma.pointCategory.create({data:{name:String(fd.get('name')),description:String(fd.get('description')||'')||null,defaultValue:Number(fd.get('defaultValue')),active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="name" className="border p-1 bg-zinc-900"/><input name="description" placeholder="description" className="border p-1 bg-zinc-900"/><input name="defaultValue" type="number" className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked/> active</label><button className="border px-2">Add</button></form>
{categories.map(c=><form key={c.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.pointCategory.delete({where:{id:c.id}}); else await prisma.pointCategory.update({where:{id:c.id},data:{name:String(fd.get('name')),description:String(fd.get('description')||'')||null,defaultValue:Number(fd.get('defaultValue')),active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={c.name} className="border p-1 bg-zinc-900"/><input name="description" defaultValue={c.description ?? ''} className="border p-1 bg-zinc-900"/><input name="defaultValue" type="number" defaultValue={c.defaultValue} className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked={c.active}/> active</label><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

</main>;
}
