import { requireAuth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { revalidatePath } from 'next/cache';
import { Nav } from '@/components/Nav';
import { RoundStatus } from '@prisma/client';

async function refresh() { 'use server'; revalidatePath('/admin'); }

function slugify(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export default async function Page() {
  await requireAuth();
  const [players, leagues, seasons, rounds, boxes, categories] = await Promise.all([
    prisma.player.findMany({ orderBy: { displayName: 'asc' } }),
    prisma.league.findMany({ orderBy: { createdAt: 'desc' } }),
    prisma.season.findMany({ include: { league: true }, orderBy: [{ year: 'desc' }] }),
    prisma.round.findMany({ include: { season: { include: { league: true } } }, orderBy: [{ startDate: 'desc' }] }),
    prisma.setBox.findMany({ include: { round: true, boxOwner: true }, orderBy: { setName: 'asc' } }),
    prisma.pointCategory.findMany({ orderBy: { name: 'asc' } }),
  ]);

  return <main className="p-8 space-y-8"><Nav /><h1 className="text-3xl font-bold">Admin Setup</h1>

<section className="space-y-2"><h2 className="text-xl font-semibold">Players</h2><p className="text-sm text-zinc-400">League members. Keep this section as your source of truth for active participants.</p>
<form action={async (fd)=>{'use server';await prisma.player.create({data:{name:String(fd.get('name')),displayName:String(fd.get('displayName')),email:String(fd.get('email')||'')||null,color:String(fd.get('color')||'#64748b'),active:fd.get('active')==='on',isAdmin:fd.get('isAdmin')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="Internal name" className="border p-1 bg-zinc-900"/><input name="displayName" placeholder="Display name" className="border p-1 bg-zinc-900"/><input name="email" placeholder="Email (optional)" className="border p-1 bg-zinc-900"/><label className="flex items-center gap-1">color <input type="color" name="color" defaultValue="#64748b" className="h-8 w-10 p-0 border"/></label><label><input type="checkbox" name="active" defaultChecked/> active</label><label><input type="checkbox" name="isAdmin"/> admin</label><button className="border px-2">Add</button></form>
{players.map(p=><form key={p.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.player.delete({where:{id:p.id}}); else await prisma.player.update({where:{id:p.id},data:{name:String(fd.get('name')),displayName:String(fd.get('displayName')),email:String(fd.get('email')||'')||null,color:String(fd.get('color')||'#64748b'),active:fd.get('active')==='on',isAdmin:fd.get('isAdmin')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={p.name} className="border p-1 bg-zinc-900"/><input name="displayName" defaultValue={p.displayName} className="border p-1 bg-zinc-900"/><input name="email" defaultValue={p.email ?? ''} className="border p-1 bg-zinc-900"/><label className="flex items-center gap-1"><span className="inline-block h-3 w-3 rounded-sm border" style={{backgroundColor:p.color}} /> <input type="color" name="color" defaultValue={p.color} className="h-8 w-10 p-0 border"/></label><label><input type="checkbox" name="active" defaultChecked={p.active}/> active</label><label><input type="checkbox" name="isAdmin" defaultChecked={p.isAdmin}/> admin</label><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section className="space-y-2"><h2 className="text-xl font-semibold">League (Yearly)</h2><p className="text-sm text-zinc-400">One yearly league (example: 2026 Box League). Type is stored in description for now.</p>
<form action={async(fd)=>{'use server'; const name=String(fd.get('name')); const year=String(fd.get('year')); const leagueType=String(fd.get('leagueType')||'Sealed Commander'); await prisma.league.create({data:{name,slug:slugify(`${name}-${year}`),description:`Type: ${leagueType}`,appDisplayName:String(fd.get('appDisplayName')||name)}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="League name" className="border p-1 bg-zinc-900"/><input name="leagueType" placeholder="League type" className="border p-1 bg-zinc-900"/><input name="year" type="number" placeholder="Year" className="border p-1 bg-zinc-900"/><input name="appDisplayName" placeholder="App display name" className="border p-1 bg-zinc-900"/><button className="border px-2">Add</button></form>
{leagues.map(l=><form key={l.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.league.delete({where:{id:l.id}}); else {const name=String(fd.get('name')); const year=String(fd.get('year')); const leagueType=String(fd.get('leagueType')); await prisma.league.update({where:{id:l.id},data:{name,slug:slugify(`${name}-${year}`),description:`Type: ${leagueType}`,appDisplayName:String(fd.get('appDisplayName'))}});} await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={l.name} className="border p-1 bg-zinc-900"/><input name="leagueType" defaultValue={(l.description || '').replace(/^Type:\s*/,'')} className="border p-1 bg-zinc-900"/><input name="year" type="number" defaultValue={new Date(l.createdAt).getUTCFullYear()} className="border p-1 bg-zinc-900"/><input name="appDisplayName" defaultValue={l.appDisplayName} className="border p-1 bg-zinc-900"/><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section className="space-y-2"><h2 className="text-xl font-semibold">Rounds (Monthly Games)</h2><p className="text-sm text-zinc-400">Each round is one monthly game day. Use play date only.</p>
<form action={async(fd)=>{'use server';const seasonId=String(fd.get('seasonId')); const monthNumber=Number(fd.get('monthNumber')); const playDate=new Date(String(fd.get('playDate'))); await prisma.round.create({data:{seasonId,name:`Round ${monthNumber}`,monthNumber,startDate:playDate,endDate:null,status:fd.get('status') as RoundStatus}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="seasonId" className="border p-1 bg-zinc-900">{seasons.map(s=><option key={s.id} value={s.id}>{s.league.name} ({s.year})</option>)}</select><input name="monthNumber" type="number" placeholder="Month #" className="border p-1 bg-zinc-900"/><input name="playDate" type="date" className="border p-1 bg-zinc-900"/><select name="status" className="border p-1 bg-zinc-900"><option>PLANNED</option><option>ACTIVE</option><option>COMPLETED</option></select><button className="border px-2">Add</button></form>
{rounds.map(r=><form key={r.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.round.delete({where:{id:r.id}}); else await prisma.round.update({where:{id:r.id},data:{seasonId:String(fd.get('seasonId')),monthNumber:Number(fd.get('monthNumber')),name:`Round ${Number(fd.get('monthNumber'))}`,startDate:new Date(String(fd.get('playDate'))),endDate:null,status:fd.get('status') as RoundStatus}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="seasonId" defaultValue={r.seasonId} className="border p-1 bg-zinc-900">{seasons.map(s=><option key={s.id} value={s.id}>{s.league.name} ({s.year})</option>)}</select><input name="monthNumber" type="number" defaultValue={r.monthNumber} className="border p-1 bg-zinc-900"/><input name="playDate" type="date" defaultValue={r.startDate.toISOString().slice(0,10)} className="border p-1 bg-zinc-900"/><select name="status" defaultValue={r.status} className="border p-1 bg-zinc-900"><option>PLANNED</option><option>ACTIVE</option><option>COMPLETED</option></select><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section className="space-y-2"><h2 className="text-xl font-semibold">Set / Boxes (per round)</h2><p className="text-sm text-zinc-400">Box details for each monthly round. Pricing/pack split fields are stored in notes in this version.</p>
<form action={async(fd)=>{'use server'; const price=String(fd.get('boxPrice')||''); const ppp=String(fd.get('packsPerPlayer')||''); const prize=String(fd.get('prizePacks')||''); const cpp=String(fd.get('cardsPerPack')||''); const extra=`price=${price}; packsPerPlayer=${ppp}; prizePacks=${prize}; cardsPerPack=${cpp}`; await prisma.setBox.create({data:{roundId:String(fd.get('roundId')),setName:String(fd.get('setName')),setCode:String(fd.get('setCode')),boxType:'Booster Box',boxOwnerId:String(fd.get('boxOwnerId')||'')||null,totalPacks:Number(fd.get('totalPacks')),notes:extra}});await refresh();}} className="flex gap-2 flex-wrap my-2"><select name="roundId" className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input name="setName" placeholder="Set name" className="border p-1 bg-zinc-900"/><input name="setCode" placeholder="Set code" className="border p-1 bg-zinc-900"/><select name="boxOwnerId" className="border p-1 bg-zinc-900"><option value="">Added by (none)</option>{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="boxPrice" type="number" step="0.01" placeholder="Box price" className="border p-1 bg-zinc-900"/><input name="totalPacks" type="number" placeholder="Total packs" className="border p-1 bg-zinc-900"/><input name="packsPerPlayer" type="number" placeholder="Packs per player" className="border p-1 bg-zinc-900"/><input name="prizePacks" type="number" placeholder="Prize packs" className="border p-1 bg-zinc-900"/><input name="cardsPerPack" type="number" placeholder="Cards per pack" className="border p-1 bg-zinc-900"/><button className="border px-2">Add</button></form>
{boxes.map(b=><form key={b.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.setBox.delete({where:{id:b.id}}); else await prisma.setBox.update({where:{id:b.id},data:{roundId:String(fd.get('roundId')),setName:String(fd.get('setName')),setCode:String(fd.get('setCode')),boxOwnerId:String(fd.get('boxOwnerId')||'')||null,totalPacks:Number(fd.get('totalPacks'))}});await refresh();}} className="flex gap-2 flex-wrap my-1"><select name="roundId" defaultValue={b.roundId} className="border p-1 bg-zinc-900">{rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input name="setName" defaultValue={b.setName} className="border p-1 bg-zinc-900"/><input name="setCode" defaultValue={b.setCode} className="border p-1 bg-zinc-900"/><select name="boxOwnerId" defaultValue={b.boxOwnerId ?? ''} className="border p-1 bg-zinc-900"><option value="">(none)</option>{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><input name="totalPacks" type="number" defaultValue={b.totalPacks} className="border p-1 bg-zinc-900"/><input readOnly value={b.notes ?? ''} className="border p-1 bg-zinc-900 min-w-[360px]"/><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

<section className="space-y-2"><h2 className="text-xl font-semibold">Point categories</h2><p className="text-sm text-zinc-400">Point rules. Suggested defaults: Win=3, Draw=2, Loss=1.</p>
<form action={async(fd)=>{'use server';await prisma.pointCategory.create({data:{name:String(fd.get('name')),description:String(fd.get('description')||'')||null,defaultValue:Number(fd.get('defaultValue')),active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-2"><input name="name" placeholder="Category name (Win/Draw/Loss)" className="border p-1 bg-zinc-900"/><input name="description" placeholder="Description" className="border p-1 bg-zinc-900"/><input name="defaultValue" type="number" placeholder="Points" className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked/> active</label><button className="border px-2">Add</button></form>
{categories.map(c=><form key={c.id} action={async(fd)=>{'use server';if(fd.get('_delete')) await prisma.pointCategory.delete({where:{id:c.id}}); else await prisma.pointCategory.update({where:{id:c.id},data:{name:String(fd.get('name')),description:String(fd.get('description')||'')||null,defaultValue:Number(fd.get('defaultValue')),active:fd.get('active')==='on'}});await refresh();}} className="flex gap-2 flex-wrap my-1"><input name="name" defaultValue={c.name} className="border p-1 bg-zinc-900"/><input name="description" defaultValue={c.description ?? ''} className="border p-1 bg-zinc-900"/><input name="defaultValue" type="number" defaultValue={c.defaultValue} className="border p-1 bg-zinc-900"/><label><input type="checkbox" name="active" defaultChecked={c.active}/> active</label><button className="border px-2">Save</button><button name="_delete" value="1" className="border px-2">Delete</button></form>)}
</section>

</main>;
}
